name: task_manager
description: A Flutter Task Management App created with Parse (Back4app) as the backend

publish_to: 'none' 
version: 1.0.0+1

author: Vijay Pratap Singh Parihar <vijay19cs130@gmail.com>
homepage: https://github.com/vijay-pratap-singh-parihar/Flutter-task-management-app-with-back4app

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  get: ^4.6.6
  get_storage: ^2.0.3
  google_fonts: ^6.1.0
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.8
  flutter_driver:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/
